### ISSUE TITLE
[Suggestion] Design and space

### ISSUE THREAD

**Issue by LeKopic** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#192]
1) Full Attacks. If there are too many modifiers - attack roll modifiers and damage roll dice are glued together.
![image](https://user-images.githubusercontent.com/42682507/167220781-482ae700-036a-438b-b2c2-5e75945b1051.png)
2) Item names field in equipment tab is a bit too small. 
![image](https://user-images.githubusercontent.com/42682507/167221000-5c7205df-7230-4e92-a2d8-74531905df9d.png)
There is quite a bit of space to be used, but it is wasted.
3) Equipment tab doesn't really support long names, which is not a problem for the majority of items except for one or two exceptions. 
![image](https://user-images.githubusercontent.com/42682507/167221430-6f8f4650-9f55-48a0-b59a-122ee66711a3.png)
Is it possible to increase "cell" height according to a number of lines of text? 
Something like this: 
![image](https://user-images.githubusercontent.com/42682507/167221656-bdfdb7df-a048-45ec-9abd-e397e2b06a7b.png)

And a side question - it is intended for backgrounds to be put into Equipment tab?

**Comment by kypvalanx** [comment]
1. it's also just ugly.  ugly and functional is my current plan until i have time to take some UI classes.  i'll see about making it easier to read once i knock the backlog down a bit
2. i dislike the whole layout for the equipment page.  i'll revisit the layout again when the backlog is reduced a bit.
3. this is actually related to one of the things i'm working on today, so, i'll take a look
4. no, equipment is populated by looking at all items on an actor and excluding by item type.  the query hasn't been updated since before bhackground existed.  i should switch it to an inclusive query.  ie, all armor, weapons, equipment, rather than all items except feats, classes, talents, etc

**Comment by kypvalanx** [comment]
1 has been addressed, idk if i released it yet

**Comment by kypvalanx** [comment]
![image](https://github.com/kypvalanx/Foundry-VTT-StarWars-SagaEdition/assets/7539264/5935d14e-551d-4516-836b-23f06bc5c909)

**Comment by kypvalanx** [comment]
I think i've handled these.  i still don't like the overall layout, but it works for now
