### ISSUE TITLE
Add Apply damage on multiple ennemy selected

### ISSUE THREAD

**Issue by Vaslayak** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#271]
So when a roll is made by rightclicking on it and having token selected you could be able to apply the damage directly instead of doing it manually
![Capture d’écran 2022-07-11 203059](https://user-images.githubusercontent.com/109117919/178383296-55db0c6f-35ac-4f2c-83d6-34d3d6537833.png)
.

As seen here:https://youtu.be/dVlj5KbQQQM?t=640

**Comment by Derinzed** [comment]
My personal preference would be to integrate the options into the card like the PF2e system.  I also appreciate having the card tell me if an attack hit instead of having to reference the targeted actor's reflex save manually.

as an example:
![image](https://user-images.githubusercontent.com/45581121/186021242-3264fcfc-f0be-4ad9-82cf-a3c0293cd46d.png)

**Comment by LeKopic** [comment]
Don't forget to account for DR. Maybe a popup window that let's you reduce damage by typing in DR value (because there are optional DRs like Strength in Numbers for Elite Trooper)?
