### ISSUE TITLE
Armor Ref Bonus are now calculated wrong.

### ISSUE THREAD

**Issue by sanpats** [kypvalanx/Foundry-VTT-StarWars-SagaEdition#72]
After the latest update, the armor Ref Bonus are now added to the Misc column of the Ref Def; instead of replacing Level, which is the correct method, as in previous version.

**Comment by kypvalanx** [comment]
you'll have to delete and readd any armor after that update. or open the armor object and change the attribute "reflexDefenseBonus" to "armorReflexDefenseBonus".  i had to make the attribute more specific because feats like Improved Defense don't interact with character level and needed a different attribute.
